version: '3.8'
services:
  rp-next:
    profiles:
      - frontend
      - fullstack
    depends_on:
      - rp-python
    build:
      context: ./rp-next
      dockerfile: Dockerfile
    volumes:
      - ./rp-next:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - fullstack-network


  rp-python:
    profiles:
      - python
      - fullstack
    build:
      context: ./rp-python
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./rp-python/src:/app/src
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/odin
      FLASK_ENV: development
    networks:
      - fullstack-network

  rp-go:
    profiles:
      - gateway
    build:
      context: ./rp-go
      dockerfile: Dockerfile
    volumes:
      - ./rp-go/:/app
    ports:
      - "8000:8000"

  postgres:
    profiles:
      - db
      - fullstack
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: odin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "odin"]
      interval: 5s
      retries: 10
    ports: 
      - "5432:5432"
    volumes:
      - ./load_data.sql:/docker-entrypoint-initdb.d/load_data.sql
      - ./data.csv:/docker-entrypoint-initdb.d/data.csv
      - ./reviews.csv:/docker-entrypoint-initdb.d/reviews.csv
    networks:
      - fullstack-network

  mongodb:
    image: mongo:6-jammy
    restart: always
    profiles:
      - auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    networks:
      - node-network

  rp-nest:
    depends_on:
      - mongodb
    profiles:
      - auth
    build:
      context: ./rp-nest
      dockerfile: Dockerfile
    volumes:
      - ./rp-nest:/usr/src/app
    ports:
      - "3001:3001"
    networks:
      - node-network

  rabbitmq:
    profiles:
      - message
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
  node-network:
    driver: bridge
  fullstack-network:
    driver: bridge
